import { ICatalogo } from "../catalogo/catalogo.interface";
import { IHistorialEntrenadoresInformacionPersonal } from "./historial-entrenadores-informacion-personal.interface";
import { IHistorialEquiposInformacionPersonal } from "./historial-equipos-informacion-personal.interface";
import { ILogrosClaveInformacionPersonal } from "./logros-clave-informacion.personal.interface";

export interface IInformacinPersonal {
  informacionPersonalId: number,
  fotoPerfilId?: number,
  alias?: string,
  altura?: number,
  peso?: number,
  estatusBusquedaJugador?: ICatalogo,
  sexo?: ICatalogo,
  medidaMano?: number,
  largoBrazo?: number,
  aperturaBrazo?: number,
  alcanceMaximo?: number,
  quienEres?: string,
  fotoPerfilPublicUrl?: string,
  alturaSaltoVertical?: number,
  distanciaSaltoHorizontal?: number,
  pesoBenchPress?: number,
  pesoSquats?: number,
  pesoPressMilitar?: number,
  pesoRepeticionBenchPress?: number,
  pesoRepeticionSquats?: number,
  pesoRepeticionPressMilitar?: number,
  tiempoDistanciaCienMts?: number,
  tiempoDistanciaUnKm?: number,
  tiempoDistanciaTresKm?: number,
  tiempoDistanciaCincoKm?: number,
  anioEmpezoAJugar?: Date ,
  manoJuego: boolean ,
  posicionJuegoUno?: ICatalogo ,
  posicionJuegoDos?: ICatalogo ,
  clavas: boolean ,
  puntosPorJuego?: number ,
  asistenciasPorJuego?: number ,
  rebotesPorJuego?: number ,
  porcentajeTirosMedia?: number ,
  porcentajeTirosTres?: number ,
  porcentajeTirosLibres?: number ,
  desdeCuandoJuegas?: Date ,
  horasEntrenamientoSemana?: number ,
  horasGymSemana?: number ,
  pertenecesClub: boolean ,
  nombreClub?: string ,
  historialEquipos?: IHistorialEquiposInformacionPersonal[] ,
  historialEntrenadores?: IHistorialEntrenadoresInformacionPersonal[] ,
  logrosClave?: ILogrosClaveInformacionPersonal[],
  objetivos?: string,
  valores?: string,
  videoBotandoId?: number ,
  videoTirandoId?: number ,
  videoColadaId?: number,
  videoEntrenandoId?: number ,
  videoJugandoId?: number,
  videoBotandoPublicUrl?: string ,
  videoTirandoPublicUrl?: string ,
  videoColadaPublicUrl?: string,
  videoEntrenandoPublicUrl?: string ,
  videoJugandoPublicUrl?: string,
  facebook?: string,
  instagram?: string,
  tiktok?: string,
  youtube?: string,
}
